export enum ActionTypePokemon {
  SET_POKEMONS = 'SET_POKEMONS',
  SET_FAVORITE = 'SET_FAVORITE',
  SET_POKEMON = 'SET_POKEMON',
  SET_INFO = 'SET_INFO',
  SET_PAGE = 'SET_PAGE',
  SET_SEARCH = 'SET_SEARCH',
  SET_LOADING = 'SET_LOADING',
  SET_ERROR = 'SET_ERROR',
}

export enum ActionTypeTheme {
  TOGGLE_THEME = 'TOGGLE_THEME',
}