export enum ActionTypePokemon {
  GET_POKEMONS = 'GET_POKEMONS',
  GET_POKEMON = 'GET_POKEMON',
  SET_POKEMONS = 'SET_POKEMONS',
  SET_POKEMON = 'SET_POKEMON',
  SET_SEARCH = 'SET_SEARCH',
  SET_LOADING = 'SET_LOADING',
  SET_ERROR = 'SET_ERROR',
}

export enum ActionTypeTheme {
  TOGGLE_THEME = 'TOGGLE_THEME',
}